# Generated by Django 4.2.6 on 2023-10-27 21:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emotion', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='emotion',
            name='text',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
